CREATE TABLE benefit_fulfillment_record (
  id                 BIGINT      NOT NULL AUTO_INCREMENT,
  fulfillment_no     VARCHAR(64) NOT NULL,
  play_biz_record_no VARCHAR(64) NOT NULL,
  benefit_item_id    VARCHAR(64) NOT NULL,
  provider_type      VARCHAR(32) NOT NULL,
  provider_product_id VARCHAR(64) NOT NULL,
  provider_order_no  VARCHAR(64) NULL COMMENT '供应方发放单号',
  grant_op_no        VARCHAR(64) NULL COMMENT '发奖幂等键，确定性派生（§4.1）',
  grant_status       VARCHAR(16) NOT NULL COMMENT '单项发放态 NOT_START/GRANTING/SUCCESS/FAILED/UNKNOWN（注意：与主单的 GRANT_* 前缀不同，二者是不同层级的枚举，不可互相赋值）',
  revoke_no          VARCHAR(64) NULL COMMENT '回收幂等键，与发奖键不复用（BR-C-11）',
  revoke_status      VARCHAR(16) NOT NULL DEFAULT 'NONE' COMMENT 'NONE/REVOKING/SUCCESS/FAILED',
  revoke_time        DATETIME(3) NULL COMMENT '回收完成时间，支撑回收/退款先后可审计（BR-B-34）',
  usage_status       VARCHAR(16) NOT NULL DEFAULT 'UNUSED' COMMENT 'UNUSED/PARTIALLY_USED/USED/EXPIRED/UNKNOWN（FR-B07）',
  last_sync_time     DATETIME(3) NULL COMMENT '使用状态最近同步时间（BR-B-28）',
  begin_time         DATETIME(3) NULL COMMENT '权益有效期起',
  end_time           DATETIME(3) NULL,
  error_code         VARCHAR(32) NULL,
  version            INT         NOT NULL DEFAULT 0,
  create_time        DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time        DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_fulfillment (fulfillment_no),
  UNIQUE KEY uk_biz_item (play_biz_record_no, benefit_item_id) COMMENT 'L3：同单同权益项至多一条履约明细',
  KEY idx_biz (play_biz_record_no),
  KEY idx_provider_order (provider_order_no) COMMENT '按供应方单号反查业务（BR-C-26）'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='履约明细，按权益项';
