CREATE TABLE play_biz_record (
  id                 BIGINT      NOT NULL AUTO_INCREMENT,
  play_biz_record_no VARCHAR(64) NOT NULL COMMENT '业务主单号',
  activity_id        VARCHAR(64) NOT NULL,
  sku_id             VARCHAR(64) NOT NULL,
  user_id            VARCHAR(64) NOT NULL COMMENT '平台用户ID',
  client_req_no      VARCHAR(64) NOT NULL COMMENT '客户端请求号，参与业务幂等键',
  quantity           INT         NOT NULL DEFAULT 1 COMMENT '购买份数，决定库存预占/释放数量',
  city_code          VARCHAR(16) NULL,
  source_channel     VARCHAR(32) NULL,
  pay_status         VARCHAR(16) NOT NULL COMMENT 'WAIT_PAY/CLOSING/PAY_SUCCESS/PAY_FAILED/CLOSED',
  grant_status       VARCHAR(16) NOT NULL DEFAULT 'NOT_START' COMMENT '主单汇总发放态 NOT_START/GRANTING/GRANT_SUCCESS/GRANT_FAILED/GRANT_UNKNOWN（终态带 GRANT_ 前缀，与明细表的单项态区分）',
  refund_status      VARCHAR(16) NOT NULL DEFAULT 'NONE' COMMENT 'NONE/REVOKING/REVOKE_FAILED/REFUNDING/REFUND_SUCCESS/REFUND_FAILED',
  order_amount       BIGINT      NOT NULL COMMENT '应付，分',
  pay_amount         BIGINT      NULL COMMENT '实付，分',
  currency           VARCHAR(8)  NOT NULL DEFAULT 'CNY',
  config_version     INT         NOT NULL,
  price_snapshot     JSON        NOT NULL,
  benefit_snapshot   JSON        NOT NULL COMMENT '权益项快照，履约据此',
  trade_no           VARCHAR(64) NULL COMMENT '支付单号',
  refund_no          VARCHAR(64) NULL COMMENT '退款单号',
  refund_amount      BIGINT      NULL COMMENT '退款金额，分',
  expire_time        DATETIME(3) NOT NULL COMMENT '支付有效期',
  version            INT         NOT NULL DEFAULT 0,
  create_time        DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time        DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_biz_no (play_biz_record_no),
  UNIQUE KEY uk_idempotent (user_id, activity_id, sku_id, client_req_no) COMMENT '业务幂等键，防重复下单',
  UNIQUE KEY uk_trade_no (trade_no),
  KEY idx_user (user_id, create_time),
  KEY idx_pay_grant (pay_status, grant_status) COMMENT '对账扫描已支付未履约'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='权益业务主单';
