CREATE TABLE play_op_record (
  id                 BIGINT      NOT NULL AUTO_INCREMENT,
  op_no              VARCHAR(64) NOT NULL,
  idempotent_key     VARCHAR(64) NOT NULL,
  play_biz_record_no VARCHAR(64) NOT NULL,
  subject_id         VARCHAR(64) NOT NULL COMMENT '操作主体用户ID（FR-C04 必填）',
  activity_id        VARCHAR(64) NOT NULL,
  op_type            VARCHAR(32) NOT NULL COMMENT 'CREATE_TRADE/PAY_CALLBACK/CLOSE_ORDER/GRANT_BENEFIT/REVOKE_BENEFIT/CREATE_REFUND/REFUND_CALLBACK/RECONCILE/MANUAL_REPAIR（查单为读操作，不建记录，只更新原记录）',
  op_seq             VARCHAR(64) NOT NULL DEFAULT '' COMMENT '至多一次的操作恒空串；可多次的取外部单号（工单号/上游退款号），严禁内部自增',
  status             VARCHAR(16) NOT NULL COMMENT '本地执行态 INIT/PROCESSING/SUCCESS/FAILED/UNKNOWN',
  downstream_result  VARCHAR(16) NULL COMMENT '下游四分类结果 SUCCESS/FAIL/PROCESSING/UNKNOWN',
  parent_op_no       VARCHAR(64) NULL COMMENT '父操作单号：CREATE_REFUND→REVOKE_BENEFIT、GRANT_BENEFIT→各权益项',
  out_order_no       VARCHAR(64) NULL COMMENT '外部单号（支付/退款/供应方）',
  recover_context    JSON        NULL COMMENT '恢复上下文，供查单与人工处置重放',
  error_code         VARCHAR(32) NULL,
  retry_count        INT         NOT NULL DEFAULT 0,
  req_digest         VARCHAR(512) NULL,
  resp_digest        VARCHAR(512) NULL,
  operator           VARCHAR(64) NULL COMMENT '人工处置操作人（BR-C-27）',
  reason             VARCHAR(256) NULL COMMENT '人工处置原因',
  version            INT         NOT NULL DEFAULT 0,
  create_time        DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time        DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  finish_time        DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_idempotent (idempotent_key),
  UNIQUE KEY uk_biz_op (play_biz_record_no, op_type, op_seq) COMMENT 'L3：每单每类操作至多一次，挡重复退款/重复履约',
  KEY idx_parent (parent_op_no) COMMENT '从父查子（BR-C-18）',
  KEY idx_out_order (out_order_no) COMMENT '按外部单号反查业务（BR-C-26）',
  KEY idx_subject_activity (subject_id, activity_id, create_time),
  KEY idx_status_recover (status, update_time) COMMENT '非终态收敛扫描'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='权益操作记录，与主单状态变更同事务';
